"""initial schema

Revision ID: 08231a3ab204
Revises: 
Create Date: 2026-09-09 21:51:48.027399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08231a3ab204'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('attendee', 'exhibitor', 'press', 'pitcher', 'investor', name='registrantcategory'), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'confirmed', name='registrantstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registrants_email'), 'registrants', ['email'], unique=False)
    op.create_index(op.f('ix_registrants_phone'), 'registrants', ['phone'], unique=False)
    op.create_index(op.f('ix_registrants_reference_number'), 'registrants', ['reference_number'], unique=True)
    op.create_table('attendee_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registrant_id', sa.UUID(), nullable=False),
    sa.Column('ticket_type', sa.Enum('general_pass', 'general', 'vip', name='tickettype'), nullable=False),
    sa.Column('wants_masterclass', sa.Boolean(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['registrant_id'], ['registrants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registrant_id')
    )
    op.create_table('exhibitor_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registrant_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('what_bringing', sa.Text(), nullable=True),
    sa.Column('portfolio_url', sa.String(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['registrant_id'], ['registrants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registrant_id')
    )
    op.create_table('investor_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registrant_id', sa.UUID(), nullable=False),
    sa.Column('organization_name', sa.String(), nullable=False),
    sa.Column('investment_interest', sa.Text(), nullable=True),
    sa.Column('budget_range', sa.String(), nullable=True),
    sa.Column('portfolio_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['registrant_id'], ['registrants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registrant_id')
    )
    op.create_table('pitcher_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registrant_id', sa.UUID(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('pitch_summary', sa.Text(), nullable=True),
    sa.Column('work_sample_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['registrant_id'], ['registrants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registrant_id')
    )
    op.create_table('press_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registrant_id', sa.UUID(), nullable=False),
    sa.Column('outlet_name', sa.String(), nullable=False),
    sa.Column('proof_type', sa.String(), nullable=True),
    sa.Column('proof_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['registrant_id'], ['registrants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registrant_id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registrant_id', sa.UUID(), nullable=False),
    sa.Column('qr_code', sa.String(), nullable=True),
    sa.Column('ticket_number', sa.String(), nullable=True),
    sa.Column('checked_in', sa.Boolean(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['registrant_id'], ['registrants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code'),
    sa.UniqueConstraint('registrant_id'),
    sa.UniqueConstraint('ticket_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('press_details')
    op.drop_table('pitcher_details')
    op.drop_table('investor_details')
    op.drop_table('exhibitor_details')
    op.drop_table('attendee_details')
    op.drop_index(op.f('ix_registrants_reference_number'), table_name='registrants')
    op.drop_index(op.f('ix_registrants_phone'), table_name='registrants')
    op.drop_index(op.f('ix_registrants_email'), table_name='registrants')
    op.drop_table('registrants')
    # ### end Alembic commands ###
