"""add scan logs table

Revision ID: 4775dbc3c1a4
Revises: f0892eb3398f
Create Date: 2026-09-26 09:35:50.917633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4775dbc3c1a4'
down_revision: Union[str, Sequence[str], None] = 'f0892eb3398f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('event_day', sa.Date(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('first_entry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('checked_in_by_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['checked_in_by_admin_id'], ['admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_logs_event_day'), 'scan_logs', ['event_day'], unique=False)
    op.create_index(op.f('ix_scan_logs_ticket_id'), 'scan_logs', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_logs_ticket_id'), table_name='scan_logs')
    op.drop_index(op.f('ix_scan_logs_event_day'), table_name='scan_logs')
    op.drop_table('scan_logs')
    # ### end Alembic commands ###
