"""add is_paid to exhibitor details

Revision ID: 95f4afdbdb47
Revises: d5edd68c1adf
Create Date: 2026-09-05 02:27:25.587767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f4afdbdb47'
down_revision: Union[str, Sequence[str], None] = 'd5edd68c1adf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exhibitor_details', sa.Column('is_paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exhibitor_details', 'is_paid')
    # ### end Alembic commands ###
