"""add pending payment references

Revision ID: f0892eb3398f
Revises: 7e99cac09635
Create Date: 2026-09-19 21:01:15.183356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0892eb3398f'
down_revision: Union[str, Sequence[str], None] = '7e99cac09635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exhibitor_details', sa.Column('pending_payment_reference', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'exhibitor_details', ['pending_payment_reference'])
    op.add_column('pitcher_details', sa.Column('pending_payment_reference', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'pitcher_details', ['pending_payment_reference'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitcher_details', type_='unique')
    op.drop_column('pitcher_details', 'pending_payment_reference')
    op.drop_constraint(None, 'exhibitor_details', type_='unique')
    op.drop_column('exhibitor_details', 'pending_payment_reference')
    # ### end Alembic commands ###
